# Generated by Django 4.0.4 on 2022-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='highest_offer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
