# Generated by Django 4.0.4 on 2022-05-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
