# Generated by Django 4.0.4 on 2022-05-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0002_alter_offer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellernotification',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firesale.offer'),
        ),
    ]
