# Generated by Django 4.0.4 on 2022-05-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firesale', '0003_sellernotification_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellernotification',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firesale.offer'),
        ),
    ]
